### ISSUE TITLE
Доделать функционал калькуляторов

### ISSUE THREAD

**Issue by gitslim** [gitslim/eplus-frontend#16]
https://new.xn--c1adkmgpem4hrai.xn--p1ai/kalkulyatory

- не показывается расчетная сумма
- не отправляется заявка??
- Disable кнопки расчета при незаполненных обязательных полях

**Comment by jeckvorobey** [comment]
не показывается расчетная сумма === готово
не отправляется заявка??  === готово

**Comment by jeckvorobey** [comment]
Disable кнопки расчета при незаполненных обязательных полях === готово
