### ISSUE TITLE
Верстка: титлы страниц

### ISSUE THREAD

**Issue by gitslim** [gitslim/eplus-frontend#17]
немного уехали 
![image](https://user-images.githubusercontent.com/24612825/123083374-a9f33200-d428-11eb-9d33-93feee336e60.png)
![image](https://user-images.githubusercontent.com/24612825/123083458-bf685c00-d428-11eb-8be4-7e39c6f5d38c.png)

**Comment by jeckvorobey** [comment]
сделал отступ сверху 20px

**Comment by gitslim** [comment]
Duplicate #55
