### ISSUE TITLE
Корректность работы форм расчёта стоимости (калькулятор) 

### ISSUE THREAD

**Issue by EnergyKir** [gitslim/eplus-frontend#23]
На обновленных страницах, например "Котельные" не работает расчет стоимости. После заполнения всех строк при нажатии кнопки "рассчитать" появляется новое окно заполнения данных. После очередного внесения данных в это окно расчет стоимости не происходит. 
Клиент вносит данные два раза и не получает цену.

**Comment by gitslim** [comment]
Done
