### ISSUE TITLE
Не корректное отображение благодарственных писем на "морде"

### ISSUE THREAD

**Issue by EnergyKir** [gitslim/eplus-frontend#53]
Благодарственные письма, при нажатии на них,  открываются на 1/10 от своего размера. Можно прочесть только шапку письма. 
![2021-09-20_16-20-56](https://user-images.githubusercontent.com/89449305/134009473-d7d5b865-c784-411d-bf6c-1e1bc85b12fc.png)

**Comment by gitslim** [comment]
done
